### ISSUE TITLE
Missing line break on second slide

### ISSUE THREAD

**Issue by Christian-Marx** [verenamarx/github-slideshow#4]
I noticed that a line break is missing before "Use the left arrow to go back!":

![slide2](https://user-images.githubusercontent.com/24615132/77146183-bf8de500-6a8a-11ea-92ef-7fb6c165fa9b.PNG)

**Comment by verenamarx** [comment]
Thanks for this information. Could you help me to fix it, please?

**Comment by Christian-Marx** [comment]
Sure, want me to grab it?

**Comment by verenamarx** [comment]
That would be great.
